### ISSUE TITLE
Initial plan for MagnetoPyElastica

### ISSUE THREAD

**Issue by armantekinalp** [armantekinalp/MagnetoPyElastica#1]
- [x] #2
- [x] Pull the code from `PyElastica`.
- [x] #4
- [x] Codecov coverage, add to the CI
- [x] Add `.gitignore`
- [x] Finish up CI, pypi release 
- [x] Add `pyproject.toml`
- [x] #3

**Comment by bhosale2** [comment]
Closed since finished.
