### ISSUE TITLE
Paper mentioned in the code

### ISSUE THREAD

**Issue by marksadward** [armantekinalp/MagnetoPyElastica#9]
May I know the title of the papers that is mentioned in the code? Thanks
![image](https://github.com/user-attachments/assets/1039bea1-77ef-4612-8b5b-19d8955f7006)

**Comment by armantekinalp** [comment]
Thanks for pointing this out here are the papers

* Wang, Liu, et al. "Hard-magnetic elastica." Journal of the Mechanics and Physics of Solids 142 (2020): 104045.
* Gu, Hongri, et al. "Magnetic cilia carpets with programmable metachronal waves." Nature communications 11.1 (2020): 2637.

**Comment by armantekinalp** [comment]
Commits 3a54f0f13ff2ddc2fbf14c121b28e0a5b34d7f3b fcf0f4bec06696001cce966a3fc576c3847f8846 d4ba9543724614f7b73f4aaffeaf48589395cbdd fixes this issue. Thus I am closing.
